export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_GOT = "USER_GOT";

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_PRODUCTS='SET_PRODUCTS';
export const ADD_PRODUCT="ADD_PRODUCT";
export const PRODUCT_FETCHED="PRODUCT_FETCHED";
export const PRODUCT_UPDATED="PRODUCT_UPDATED";
export const PRODUCT_DELETED="PRODUCT_DELETED";

export const USER_FETCHED = "USER_FETCHED";
